#!/usr/bin/env python
import optparse
from colorama import Style, Fore
import os
import sys
import py_compile
import datetime
import random
import string


parser = optparse.OptionParser()

parser.add_option('-f', '--file',
    action="store", dest="file",
    help="File to insert junk code", default="")

options, args = parser.parse_args()

def id_generator(size=6, chars=string.ascii_uppercase + string.digits):
       return ''.join(random.choice(chars) for _ in range(size))

class color:
   PURPLE = '\033[95m'
   CYAN = '\033[96m'
   DARKCYAN = '\033[36m'
   BLUE = '\033[94m'
   GREEN = '\033[92m'
   YELLOW = '\033[93m'
   RED = '\033[91m'
   BOLD = '\033[1m'
   UNDERLINE = '\033[4m'
   END = '\033[0m'

def insert_junk_code(fname):
    File = open(fname, "a+")
    print color.GREEN + "(+)" + color.END + " Writting junk codes ..."
    File.write("\n  # This comment Was Generated By DiviCrypt 1.0 "+id_generator())
    File.write("\n  # This comment Was Generated By DiviCrypt 1.0 "+id_generator())
    File.write("\n  # This comment Was Generated By DiviCrypt 1.0 "+id_generator())
    File.write("\n  # This comment Was Generated By DiviCrypt 1.0 "+id_generator())
    File.write("\n  # This comment Was Generated By DiviCrypt 1.0 "+id_generator())
    File.close()


insert_junk_code(options.file)
